model:
  name: tv
  cnn_block:
    n_ch_in: 2 #must be two for the complex-valued input image
    n_ch_out: 1 #must be one to map the complex-valued input image to one spatially adaptive parameter map
    n_enc_stages: 3
    n_convs_per_stage: 2
    n_filters: 16
  n_iterations: 128

training:
  n_training: 4
  n_validation: 2
  n_epochs: 12
  batch_size: 2
  noise_std:
    low: 0.075
    high: 0.30
  n_k1: [120, 160, 200]
  learning_rate: 0.0001
  weight_decay: 0.00001
  learning_rate_global_scaling: 0.1
  

